[build]
  command = "npm run build"
  publish = "build"  # Adjust this if your build output directory is different

[context.production.environment]
  NODE_VERSION = "14"

[context.branch-deploy.environment]
  NODE_VERSION = "14"

[context.deploy-preview.environment]
  NODE_VERSION = "14"

