services:
  - type: web
    name: mtg-pile
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
